name: Update Redirect
on:
  issues:
    types: [opened, edited]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate new file
        id: generate_file
        run: |
          cd r
          echo '${{ github.event.issue.body }}' > body.temp
          title=$(sed '1q;d' body.temp)
          description=$(sed '2q;d' body.temp)
          image=$(sed '3q;d' body.temp)
          site_name=$(sed '4q;d' body.temp)
          url=https://anderick.github.io/issue-redir/r/${{ github.event.issue.node_id }}.html
          destination=${{ github.event.issue.title }}
          template="$(cat ../redir.template)"
          eval "echo \"${template}\"" > ${filename}
          cd ../

      - name: Commit files
        run: |
          git config --local user.name  ${{ github.actor }}
          git add ./r
          git commit -m "Updating file ${{ github.event.issue.number }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          branch: ${{ github.ref }}

      - name: Add comment with the link
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            [https://anderick.github.io/issue-redir/r/${{ github.event.issue.node_id }}.html](https://anderick.github.io/issue-redir/r/${{ github.event.issue.node_id }}.html)
          reactions: heart
