name: Update Redirect
on:
  issues:
    types: [opened, edited]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate new file
        run: |
          cd r
          echo '${{ github.event.issue.body }}' > body.temp
          title=$(sed '1q;d')
          description=$(sed '2q;d')
          image=$(sed '3q;d')
          site_name=$(sed '4q;d')
          url=https://something/${{ github.event.issue.number }}
          destination=${{ github.event.issue.title }}
          template="$(cat ../redir.template)"
          eval "echo \"${template}\"" > ${{ github.event.issue.number }}.html
          cd ../

      - name: Commit files
        run: |
          git config --local user.name  ${{ github.actor }}
          git add ./r
          git commit -m "Updating file ${{ github.event.issue.number }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          branch: ${{ github.ref }}
